In [1]:
import pandas as pd, numpy as np

In [2]:
file_path = r"C:\Users\rahul\Desktop\credit scoring project\german_credit_data.csv"
df= pd.read_csv(file_path)

In [3]:
df.head()

,laufkont,laufzeit,moral,verw,hoehe,sparkont,beszeit,rate,famges,buerge,...,verm,alter,weitkred,wohn,bishkred,beruf,pers,telef,gastarb,kredit
0,1,18,4,2,1049,1,2,4,2,1,...,2,21,3,1,1,3,2,1,2,1
1,1,9,4,0,2799,1,3,2,3,1,...,1,36,3,1,2,3,1,1,2,1
2,2,12,2,9,841,2,4,2,2,1,...,1,23,3,1,1,2,2,1,2,1
3,1,12,4,0,2122,1,3,3,3,1,...,1,39,3,1,2,2,1,1,1,1
4,1,12,4,0,2171,1,3,4,3,1,...,2,38,1,2,2,2,2,1,1,1

In [4]:
df.shape

(1000, 21)

In [5]:
df = df.rename(columns={
    "laufkont": "Checking_Account_Status",
    "laufzeit": "Loan_Duration_Months",
    "moral": "Credit_History",
    "verw": "Loan_Purpose",
    "hoehe": "Loan_Amount",
    "sparkont": "Savings_Account_Status",
    "beszeit": "Employment_Duration",
    "rate": "Installment_Rate_Percent",
    "famges": "Personal_Status_Sex",
    "buerge": "Guarantors",
    "wohnzeit": "Years_at_Current_Address",
    "verm": "Property",
    "alter": "Age",
    "weitkred": "Other_Installment_Plans",
    "wohn": "Housing",
    "bishkred": "Number_of_Existing_Credits",
    "beruf": "Job",
    "pers": "Number_of_Dependents",
    "telef": "Telephone",
    "gastarb": "Foreign_Worker",
    "kredit": "Default"
})

In [6]:
df.columns

Index(['Checking_Account_Status', 'Loan_Duration_Months', 'Credit_History',
       'Loan_Purpose', 'Loan_Amount', 'Savings_Account_Status',
       'Employment_Duration', 'Installment_Rate_Percent',
       'Personal_Status_Sex', 'Guarantors', 'Years_at_Current_Address',
       'Property', 'Age', 'Other_Installment_Plans', 'Housing',
       'Number_of_Existing_Credits', 'Job', 'Number_of_Dependents',
       'Telephone', 'Foreign_Worker', 'Default'],
      dtype='str')

In [7]:
df.head()

,Checking_Account_Status,Loan_Duration_Months,Credit_History,Loan_Purpose,Loan_Amount,Savings_Account_Status,Employment_Duration,Installment_Rate_Percent,Personal_Status_Sex,Guarantors,...,Property,Age,Other_Installment_Plans,Housing,Number_of_Existing_Credits,Job,Number_of_Dependents,Telephone,Foreign_Worker,Default
0,1,18,4,2,1049,1,2,4,2,1,...,2,21,3,1,1,3,2,1,2,1
1,1,9,4,0,2799,1,3,2,3,1,...,1,36,3,1,2,3,1,1,2,1
2,2,12,2,9,841,2,4,2,2,1,...,1,23,3,1,1,2,2,1,2,1
3,1,12,4,0,2122,1,3,3,3,1,...,1,39,3,1,2,2,1,1,1,1
4,1,12,4,0,2171,1,3,4,3,1,...,2,38,1,2,2,2,2,1,1,1

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Checking_Account_Status     1000 non-null   int64
 1   Loan_Duration_Months        1000 non-null   int64
 2   Credit_History              1000 non-null   int64
 3   Loan_Purpose                1000 non-null   int64
 4   Loan_Amount                 1000 non-null   int64
 5   Savings_Account_Status      1000 non-null   int64
 6   Employment_Duration         1000 non-null   int64
 7   Installment_Rate_Percent    1000 non-null   int64
 8   Personal_Status_Sex         1000 non-null   int64
 9   Guarantors                  1000 non-null   int64
 10  Years_at_Current_Address    1000 non-null   int64
 11  Property                    1000 non-null   int64
 12  Age                         1000 non-null   int64
 13  Other_Installment_Plans     1000 non-null   int64
 14  Housing                     1000 non-null   int64
 15  Number_of_Existing_Credits  1000 non-null   int64
 16  Job                         1000 non-null   int64
 17  Number_of_Dependents        1000 non-null   int64
 18  Telephone                   1000 non-null   int64
 19  Foreign_Worker              1000 non-null   int64
 20  Default                     1000 non-null   int64
dtypes: int64(21)
memory usage: 164.2 KB

In [79]:
corr = df.corr(numeric_only=True)

corr['Default'].sort_values(ascending=False)

Default                       1.000000
Checking_Account_Status       0.350847
Credit_History                0.228785
Savings_Account_Status        0.178943
Employment_Duration           0.116002
Other_Installment_Plans       0.109844
Age                           0.091272
Personal_Status_Sex           0.088184
Number_of_Existing_Credits    0.045732
Telephone                     0.036466
Guarantors                    0.025137
Housing                       0.018119
Years_at_Current_Address     -0.002967
Number_of_Dependents         -0.003015
Loan_Purpose                 -0.017979
Job                          -0.032735
Installment_Rate_Percent     -0.072404
Foreign_Worker               -0.082079
Property                     -0.142612
Loan_Amount                  -0.154740
Loan_Duration_Months         -0.214927
Name: Default, dtype: float64

In [9]:
df= df.drop(columns=['Loan_Purpose'] )

In [10]:
df= df.drop(columns=['Years_at_Current_Address', 'Number_of_Dependents'] )

In [26]:
df.to_csv('cleaned_file.csv', index=False )

In [24]:
df.columns
df.shape

(1000, 18)

In [15]:
y= df['Default']

X= df.drop(columns= ['Default'])

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [17]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [22]:
print(scaler.feature_names_in_)
print(X_train.shape)

['Checking_Account_Status' 'Loan_Duration_Months' 'Credit_History'
 'Loan_Amount' 'Savings_Account_Status' 'Employment_Duration'
 'Installment_Rate_Percent' 'Personal_Status_Sex' 'Guarantors' 'Property'
 'Age' 'Other_Installment_Plans' 'Housing' 'Number_of_Existing_Credits'
 'Job' 'Telephone' 'Foreign_Worker']
(800, 17)

In [58]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    class_weight='balanced',
    random_state=42
)

model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', random_state=42)

In [59]:
from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    classification_report
)

pred = model.predict(X_test)
prob = model.predict_proba(X_test)[:,1]

print("Accuracy:", accuracy_score(y_test,pred))
print("AUC:", roc_auc_score(y_test,prob))
print(classification_report(y_test,pred))

Accuracy: 0.72
AUC: 0.813095238095238
              precision    recall  f1-score   support

           0       0.52      0.73      0.61        60
           1       0.86      0.71      0.78       140

    accuracy                           0.72       200
   macro avg       0.69      0.72      0.70       200
weighted avg       0.76      0.72      0.73       200

In [60]:
train_prob = model.predict_proba(X_train)[:,1]
test_prob = model.predict_proba(X_test)[:,1]

print("Train AUC:", roc_auc_score(y_train, train_prob))
print("Test AUC:", roc_auc_score(y_test, test_prob))

Train AUC: 0.7997916666666667
Test AUC: 0.813095238095238

In [61]:
importance = pd.DataFrame({
    'Feature': x.columns,
    'Coefficient': model.coef_[0]
})

importance.sort_values(
    by='Coefficient',
    ascending=False
)

                       Feature  Coefficient
0      Checking_Account_Status     0.697959
5       Savings_Account_Status     0.408650
2               Credit_History     0.377452
14                     Housing     0.231387
8          Personal_Status_Sex     0.203994
13     Other_Installment_Plans     0.184197
6          Employment_Duration     0.139824
9                   Guarantors     0.133192
18                   Telephone     0.114721
10    Years_at_Current_Address     0.079467
3                 Loan_Purpose     0.075306
17        Number_of_Dependents     0.034271
12                         Age     0.022708
16                         Job    -0.032734
15  Number_of_Existing_Credits    -0.128403
11                    Property    -0.184468
4                  Loan_Amount    -0.236210
1         Loan_Duration_Months    -0.268259
7     Installment_Rate_Percent    -0.303380
19              Foreign_Worker    -0.309906

In [30]:
prob = model.predict_proba(x)[:,1]

df['Credit_Score'] = (
    900 - (prob * 600)
).astype(int)

C:\Users\rahul\anaconda3\envs\credit-scoring\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

In [32]:
pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in C:\Users\rahul\anaconda3\envs\credit-scoring\Lib\site-packages (from xgboost) (2.4.6)
Requirement already satisfied: scipy in C:\Users\rahul\anaconda3\envs\credit-scoring\Lib\site-packages (from xgboost) (1.17.1)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.5/101.7 MB 3.3 MB/s eta 0:00:31
    --------------------------------------- 1.3/101.7 MB 4.1 MB/s eta 0:00:25
   - -------------------------------------- 2.6/101.7 MB 4.9 MB/s eta 0:00:21
   - -------------------------------------- 4.2/101.7 MB 5.6 MB/s eta 0:00:18
   -- ------------------------------------- 5.5/101.7 MB 5.9 MB/s eta 0:00:17
   -- ------------------------------------- 6.8/101.7 MB 5.9 MB/s eta 0:00:17
   --- ------------------------------------ 8.4/101.7 MB 6.1 MB/s eta 0:00:16
   --- ------------------------------------ 9.7/101.7 MB 6.2 MB/s eta 0:00:15
   ---- ----------------------------------- 11.0/101.7 MB 6.2 MB/s eta 0:00:15
   ---- ----------------------------------- 12.6/101.7 MB 6.3 MB/s eta 0:00:15
   ----- ---------------------------------- 13.9/101.7 MB 6.4 MB/s eta 0:00:14
   ------ --------------------------------- 15.5/101.7 MB 6.4 MB/s eta 0:00:14
   ------ --------------------------------- 16.8/101.7 MB 6.4 MB/s eta 0:00:14
   ------- -------------------------------- 18.1/101.7 MB 6.4 MB/s eta 0:00:14
   ------- -------------------------------- 19.4/101.7 MB 6.4 MB/s eta 0:00:13
   -------- ------------------------------- 21.0/101.7 MB 6.4 MB/s eta 0:00:13
   -------- ------------------------------- 22.5/101.7 MB 6.5 MB/s eta 0:00:13
   --------- ------------------------------ 23.6/101.7 MB 6.4 MB/s eta 0:00:13
   --------- ------------------------------ 25.2/101.7 MB 6.5 MB/s eta 0:00:12
   ---------- ----------------------------- 26.7/101.7 MB 6.5 MB/s eta 0:00:12
   ----------- ---------------------------- 28.3/101.7 MB 6.5 MB/s eta 0:00:12
   ----------- ---------------------------- 29.9/101.7 MB 6.6 MB/s eta 0:00:11
   ------------ --------------------------- 31.2/101.7 MB 6.6 MB/s eta 0:00:11
   ------------ --------------------------- 32.5/101.7 MB 6.6 MB/s eta 0:00:11
   ------------ --------------------------- 32.8/101.7 MB 6.5 MB/s eta 0:00:11
   ------------- -------------------------- 34.1/101.7 MB 6.4 MB/s eta 0:00:11
   ------------- -------------------------- 34.9/101.7 MB 6.3 MB/s eta 0:00:11
   -------------- ------------------------- 36.2/101.7 MB 6.3 MB/s eta 0:00:11
   -------------- ------------------------- 37.7/101.7 MB 6.3 MB/s eta 0:00:11
   --------------- ------------------------ 39.1/101.7 MB 6.3 MB/s eta 0:00:10
   --------------- ------------------------ 40.6/101.7 MB 6.4 MB/s eta 0:00:10
   ---------------- ----------------------- 42.2/101.7 MB 6.4 MB/s eta 0:00:10
   ----------------- ---------------------- 43.5/101.7 MB 6.4 MB/s eta 0:00:10
   ----------------- ---------------------- 45.1/101.7 MB 6.4 MB/s eta 0:00:09
   ------------------ --------------------- 46.7/101.7 MB 6.5 MB/s eta 0:00:09
   ------------------ --------------------- 47.7/101.7 MB 6.4 MB/s eta 0:00:09
   ------------------- -------------------- 49.3/101.7 MB 6.4 MB/s eta 0:00:09
   -------------------- ------------------- 50.9/101.7 MB 6.5 MB/s eta 0:00:08
   -------------------- ------------------- 51.9/101.7 MB 6.5 MB/s eta 0:00:08
   -------------------- ------------------- 53.0/101.7 MB 6.4 MB/s eta 0:00:08
   --------------------- ------------------ 54.5/101.7 MB 6.4 MB/s eta 0:00:08
   ---------------------- ----------------- 56.1/101.7 MB 6.4 MB/s eta 0:00:08
   ---------------------- ----------------- 57.7/101.7 MB 6.5 MB/s eta 0:00:07
   ----------------------- ---------------- 59.0/101.7 MB 6.5 MB/s eta 0:00:07
   ----------------------- ---------------- 60.6/101.7 MB 6.5 MB/s eta 0:00:07
   ------------------------ --------------- 61.9/101.7 MB 6.5 MB/s eta 0:00:07
   ------------------------ --------------- 63.4/101.7 MB 6.5 MB/s eta 0:00:06
   ------------------------- -------------- 65.0/101.7 MB 6.5 MB/s eta 0:00:06
   -------------------------- ------------- 66.3/101.7 MB 6.5 MB/s eta 0:00:06
   -------------------------- ------------- 68.2/101.7 MB 6.5 MB/s eta 0:00:06
   --------------------------- ------------ 69.5/101.7 MB 6.5 MB/s eta 0:00:05
   --------------------------- ------------ 70.8/101.7 MB 6.5 MB/s eta 0:00:05
   ---------------------------- ----------- 72.4/101.7 MB 6.6 MB/s eta 0:00:05
   ---------------------------- ----------- 73.7/101.7 MB 6.6 MB/s eta 0:00:05
   ----------------------------- ---------- 75.2/101.7 MB 6.6 MB/s eta 0:00:05
   ------------------------------ --------- 76.8/101.7 MB 6.6 MB/s eta 0:00:04
   ------------------------------ --------- 78.1/101.7 MB 6.6 MB/s eta 0:00:04
   ------------------------------- -------- 79.4/101.7 MB 6.6 MB/s eta 0:00:04
   ------------------------------- -------- 81.0/101.7 MB 6.6 MB/s eta 0:00:04
   -------------------------------- ------- 82.6/101.7 MB 6.6 MB/s eta 0:00:03
   -------------------------------- ------- 83.1/101.7 MB 6.5 MB/s eta 0:00:03
   -------------------------------- ------- 83.9/101.7 MB 6.5 MB/s eta 0:00:03
   --------------------------------- ------ 84.7/101.7 MB 6.5 MB/s eta 0:00:03
   --------------------------------- ------ 86.0/101.7 MB 6.4 MB/s eta 0:00:03
   ---------------------------------- ----- 87.6/101.7 MB 6.5 MB/s eta 0:00:03
   ----------------------------------- ---- 89.1/101.7 MB 6.5 MB/s eta 0:00:02
   ----------------------------------- ---- 90.4/101.7 MB 6.5 MB/s eta 0:00:02
   ------------------------------------ --- 91.8/101.7 MB 6.5 MB/s eta 0:00:02
   ------------------------------------ --- 93.1/101.7 MB 6.5 MB/s eta 0:00:02
   ------------------------------------- -- 94.6/101.7 MB 6.5 MB/s eta 0:00:02
   ------------------------------------- -- 96.2/101.7 MB 6.5 MB/s eta 0:00:01
   -------------------------------------- - 97.8/101.7 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------  99.4/101.7 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------  100.9/101.7 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 6.4 MB/s  0:00:16
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0
Note: you may need to restart the kernel to use updated packages.

In [65]:
from xgboost import XGBClassifier

model = XGBClassifier(
    n_estimators=100,
    max_depth=3,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=5,
    random_state=42
)

model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=5, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [66]:
from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    classification_report
)

pred = model.predict(X_test)
prob = model.predict_proba(X_test)[:,1]

print("Accuracy:", accuracy_score(y_test,pred))
print("AUC:", roc_auc_score(y_test,prob))
print(classification_report(y_test,pred))

Accuracy: 0.795
AUC: 0.830952380952381
              precision    recall  f1-score   support

           0       0.70      0.55      0.62        60
           1       0.82      0.90      0.86       140

    accuracy                           0.80       200
   macro avg       0.76      0.73      0.74       200
weighted avg       0.79      0.80      0.79       200

In [67]:
train_prob = model.predict_proba(X_train)[:,1]
test_prob = model.predict_proba(X_test)[:,1]

print("Train AUC:", roc_auc_score(y_train, train_prob))
print("Test AUC:", roc_auc_score(y_test, test_prob))

Train AUC: 0.8925148809523809
Test AUC: 0.830952380952381

In [68]:
def find_credit_score(new_customer):
    new_df = pd.DataFrame([new_customer])

    new_df_scaled = scaler.transform(new_df)

    pred = model.predict(new_df_scaled)[0]

    predict = "good" if pred == 1 else "bad"

    prob = model.predict_proba(new_df_scaled)
    good_prob = prob[:, 1]

    credit_score = int(300 + good_prob[0] * 600)

    return {
        "prediction": predict,
        "credit_score": credit_score
    }

In [69]:
new_customer = {
    'Checking_Account_Status': 2,
    'Loan_Duration_Months': 24,
    'Credit_History': 1,
    'Loan_Purpose': 3,
    'Loan_Amount': 5000,
    'Savings_Account_Status': 2,
    'Employment_Duration': 3,
    'Installment_Rate_Percent': 2,
    'Personal_Status_Sex': 1,
    'Guarantors': 1,
    'Years_at_Current_Address': 3,
    'Property': 2,
    'Age': 35,
    'Other_Installment_Plans': 1,
    'Housing': 2,
    'Number_of_Existing_Credits': 1,
    'Job': 2,
    'Number_of_Dependents': 1,
    'Telephone': 1,
    'Foreign_Worker': 1
}

predictions= find_credit_score(new_customer)

C:\Users\rahul\anaconda3\envs\credit-scoring\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

In [70]:
print(predictions)

{'prediction': 'good', 'credit_score': 786}

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=6,
    min_samples_leaf=5,
    random_state=42
)

rf.fit(X_train, y_train)

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    classification_report
)

pred = rf.predict(X_test)

prob = rf.predict_proba(X_test)[:, 1]

print("Accuracy:", accuracy_score(y_test, pred))
print("AUC:", roc_auc_score(y_test, prob))
print(classification_report(y_test, pred))